In [3]:
import requests
import pandas as pd

headers = {
    "accept": "application/json",
    "Authorization": "Bearer eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiI0MWFiZmRkMDM4MGUwZjlkN2QxOWQxZjUyMzE4M2IwMyIsIm5iZiI6MTc4NTQ3MDQ1MS4zMzYsInN1YiI6IjZhNmMxZGYzYzQ2ZDQ3NjMwYjc3MTQzMCIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.bnmwHQTx9Ybfpq9YrhZRNJlpdYJseX16dn6LWV3jCn0"
}

movies = []

for page in range(1, 11):      # Top 200 movies

    url = f"https://api.themoviedb.org/3/movie/popular?language=en-US&page={page}"

    response = requests.get(url, headers=headers)

    data = response.json()

    for movie in data["results"]:

        movies.append({
            "Movie ID": movie["id"],
            "Title": movie["title"],
            "Release Date": movie["release_date"],
            "Language": movie["original_language"],
            "Popularity": movie["popularity"],
            "Vote Average": movie["vote_average"],
            "Vote Count": movie["vote_count"],
            "Adult": movie["adult"],
            "Genre IDs": movie["genre_ids"]
        })

movies_df = pd.DataFrame(movies)

movies_df.head()

,Movie ID,Title,Release Date,Language,Popularity,Vote Average,Vote Count,Adult,Genre IDs
0,969681,Spider-Man: Brand New Day,2026-07-28,en,1519.8510,8.000,328,False,"[878, 28, 12]"
1,1368337,The Odyssey,2026-07-15,en,1166.5658,7.900,1871,False,"[12, 28, 14]"
2,1081003,Supergirl,2026-06-24,en,630.4075,6.751,1154,False,"[28, 12, 878]"
3,454639,Masters of the Universe,2026-06-03,en,486.7027,7.279,1358,False,"[28, 14, 878]"
4,1275779,Disclosure Day,2026-06-10,en,397.2506,7.410,2050,False,"[878, 53]"

In [4]:
url = "https://api.themoviedb.org/3/genre/movie/list?language=en"

response = requests.get(url, headers=headers)

genres = response.json()["genres"]

genre_df = pd.DataFrame(genres)

genre_df

       id             name
0      28           Action
1      12        Adventure
2      16        Animation
3      35           Comedy
4      80            Crime
5      99      Documentary
6      18            Drama
7   10751           Family
8      14          Fantasy
9      36          History
10     27           Horror
11  10402            Music
12   9648          Mystery
13  10749          Romance
14    878  Science Fiction
15  10770         TV Movie
16     53         Thriller
17  10752              War
18     37          Western

In [5]:
details = []

for movie_id in movies_df["Movie ID"]:

    url = f"https://api.themoviedb.org/3/movie/{movie_id}"

    response = requests.get(url, headers=headers)

    movie = response.json()

    details.append({
        "Movie ID": movie["id"],
        "Runtime": movie["runtime"],
        "Budget": movie["budget"],
        "Revenue": movie["revenue"],
        "Status": movie["status"],
        "Tagline": movie["tagline"],
        "Homepage": movie["homepage"],
        "IMDb": movie["imdb_id"],
        "Production Countries": ", ".join(
            [x["name"] for x in movie["production_countries"]]
        )
    })

details_df = pd.DataFrame(details)

In [6]:
final_df = movies_df.merge(details_df, on="Movie ID")

final_df.head()

,Movie ID,Title,Release Date,Language,Popularity,Vote Average,Vote Count,Adult,Genre IDs,Runtime,Budget,Revenue,Status,Tagline,Homepage,IMDb,Production Countries
0,969681,Spider-Man: Brand New Day,2026-07-28,en,1519.8510,8.000,328,False,"[878, 28, 12]",145,225000000,50000000,Released,A brand new day starts now.,https://spidermanbrandnewday.movie,tt22084616,United States of America
1,1368337,The Odyssey,2026-07-15,en,1166.5658,7.900,1871,False,"[12, 28, 14]",173,250000000,683184575,Released,Defy the gods.,https://www.universalpictures.com/movies/the-o...,tt33764258,"United Kingdom, United States of America"
2,1081003,Supergirl,2026-06-24,en,630.4075,6.751,1154,False,"[28, 12, 878]",108,175000000,124712685,Released,Truth. Justice. Whatever.,https://www.supergirlmovie.com,tt8814476,United States of America
3,454639,Masters of the Universe,2026-06-03,en,486.7027,7.279,1358,False,"[28, 14, 878]",141,200000000,113749618,Released,"Legends aren't born, they're forged.",https://www.amazon.com/salp/motu?hhf=,tt0427340,United States of America
4,1275779,Disclosure Day,2026-06-10,en,397.2506,7.410,2050,False,"[878, 53]",146,115000000,239022890,Released,We deserve to know.,https://www.disclosuredaymovie.com,tt15047880,United States of America

In [ ]:
#dropping duplicates of the same movies
inal_df = final_df.drop_duplicates(subset="Movie ID")

In [ ]:
# creating a new table called movie_genres
movie_genres = []

for _, row in movies_df.iterrows():
    movie_id = row["Movie ID"]

    for genre in row["Genre IDs"]:
        movie_genres.append({
            "Movie ID": movie_id,
            "Genre ID": genre
        })

movie_genres_df = pd.DataFrame(movie_genres)

movie_genres_df.head()

   Movie ID  Genre ID
0    969681       878
1    969681        28
2    969681        12
3   1368337        12
4   1368337        28